##Multi-Linear_Regression On Advertising Data-Set

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn
import pylab as pl

In [2]:
data = pd.read_csv('data/Advertising.csv')
data.head()

Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [3]:
data = data.drop(['Unnamed: 0'], axis = 1)
data.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [4]:
data.tail()

TV  radio  newspaper  sales
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
TV           200 non-null float64
radio        200 non-null float64
newspaper    200 non-null float64
sales        200 non-null float64
dtypes: float64(4)
memory usage: 6.4 KB


In [6]:
data.describe()

TV       radio   newspaper       sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000

In [7]:
data.index

RangeIndex(start=0, stop=200, step=1)

In [8]:
data.columns

Index(['TV', 'radio', 'newspaper', 'sales'], dtype='object')

In [10]:
x = data[['TV', 'radio', 'newspaper']]
x.head(2)

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1

In [11]:
y = data['sales']
y.head()

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: sales, dtype: float64

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [14]:
x_train.shape

(160, 3)

In [15]:
x_test.shape

(40, 3)

In [16]:
y_train.shape

(160,)

In [17]:
y_test.shape

(40,)

In [18]:
from sklearn import linear_model
regr = linear_model.LinearRegression()
regr.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [19]:
regr.coef_

array([0.04522267, 0.18920121, 0.00544749])

In [20]:
regr.intercept_

2.709231351347624

In [23]:
ypred = regr.predict(x_test)
ypred

array([20.95557865, 10.55294328,  7.55210143, 14.41917879,  9.56001972,
       22.9027845 ,  9.9012075 , 10.27434079, 12.50807937,  9.72429414,
       19.21273221, 13.628152  , 21.96007703, 16.25814985,  9.31526855,
       19.76700342, 14.89005283, 18.11763205, 18.57841554,  5.6236229 ,
        8.66175625, 19.16877026, 15.24594568, 12.22859252, 10.13232634,
       12.51972791, 19.38609707, 12.59165068,  7.34223412, 16.96306652,
       17.71343994, 10.03575734, 15.80668663, 13.3211061 ,  9.76038369,
        8.58143671, 14.78378483,  6.49098272, 21.51077888,  4.43492682])

In [26]:
regr.score(x_test, ypred)

1.0

In [27]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
mean_absolute_error(y_test, ypred)

1.221080988176526

In [28]:
mean_squared_error(y_test, ypred)

2.3794597763521046

In [29]:
r2_score(y_test, ypred)

0.908372517496005

In [32]:
from sklearn.model_selection import cross_val_score
cv_results = cross_val_score(regr, x_train, y_train, cv = 20)
cv_results

array([0.94198898, 0.89638868, 0.96391839, 0.83866915, 0.73528669,
       0.53937781, 0.82349277, 0.93059041, 0.73722931, 0.94949562,
       0.90468372, 0.9264014 , 0.36008427, 0.94004414, 0.90805155,
       0.92212056, 0.863351  , 0.94250246, 0.57171676, 0.89804933])

In [33]:
np.min(cv_results)

0.36008427107281327

In [34]:
np.max(cv_results)

0.9639183923088993

In [35]:
np.mean(cv_results)

0.8296721504335725

Simple Linear Regression For the Above Problem:

In [36]:
x = data[['TV']]
x.head()

TV
0  230.1
1   44.5
2   17.2
3  151.5
4  180.8

In [37]:
y = data['sales']
y.head()

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: sales, dtype: float64

In [47]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size = 0.7)

In [48]:
x_train.shape

(140, 1)

In [49]:
x_test.shape

(60, 1)

In [50]:
y_train.shape

(140,)

In [51]:
y_test.shape

(60,)

In [52]:
from sklearn.linear_model import LinearRegression
regr = LinearRegression()
regr.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [53]:
regr.coef_

array([0.04806299])

In [54]:
regr.intercept_

7.0121995714895675

In [55]:
regr.rank_

1

In [56]:
yhat = regr.predict(x_test)
yhat

array([13.71698733, 16.86511348, 19.28748842, 13.55837945, 12.64518255,
       15.19252127, 11.94826913, 10.3381588 ,  7.83888308, 16.04323628,
       19.64796088, 11.52531477, 20.64286487,  7.6466311 , 19.84021286,
       16.50944732, 17.57644581, 15.70198901, 10.63134307, 20.98411213,
        8.84820597, 10.64095567,  9.07890834, 11.3234502 ,  9.33364222,
       12.92875422,  7.91578387, 14.97143149, 16.19703786, 18.5377057 ,
        8.33393193, 14.8704992 , 13.64008654, 13.34209597, 12.28951639,
        7.83888308,  9.71333987, 17.41303162,  7.27173974, 17.51396391,
        8.21858074, 19.75850577, 13.51031645,  9.58356979, 15.89904729,
       20.93604914, 16.95162688,  9.16061543, 18.42235451, 15.24539056,
       12.43851167, 11.68392266, 11.69834155, 16.29797015, 19.77773096,
       16.03842998, 17.13907255,  8.30028783, 18.46080491, 11.63585966])

In [60]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [61]:
mean_absolute_error(y_test, yhat)

2.371725226982095

In [63]:
mean_squared_error(y_test, yhat)

9.83902469895592

In [64]:
r2_score(y_test, yhat)

0.600650170023027

In [65]:
from sklearn.model_selection import cross_val_score
cv_results = cross_val_score(regr, x_train, y_train, cv = 20)
cv_results

array([ 0.75769446,  0.69029931,  0.47429592,  0.51547569,  0.72735793,
        0.48008096,  0.79747038,  0.20867106,  0.61191108,  0.48133574,
       -0.16834863, -0.16716744,  0.20136159,  0.60989502,  0.86759586,
        0.56291932,  0.7977928 ,  0.21451461,  0.62147838, -0.37851214])

In [66]:
np.min(cv_results)

-0.37851214311162784

In [67]:
np.max(cv_results)

0.8675958590037586

In [69]:
np.mean(cv_results)

0.4453060941880083